### PR TITLE
[setup.py] Work around pip bug with "pip install -e ."

### PR DESCRIPTION
**Pull request by behdad**
See https://github.com/pypa/pip/issues/7953

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
I don't use pip install -e --user together since I use virtual environments for development, but I don't see why this should not work. So LGTM as long as it doesn't break anything else

**Comment by behdad** [comment]
Thanks.

**Comment by behdad** [comment]
I don't have permission to merge.

**Comment by anthrotype** [comment]
I sent invitation, try again afterwards and let me know otherwise

**Pull request merged**
