### PR TITLE
Rework testsuite

### PR DESCRIPTION
**Pull request by madig**

### CODE REVIEW

**Comment by madig** [comment]
I marked one test as skip because I don't know whether the code is broken or I'm doing it wrong. I think the other test directory can go now?

**Comment by madig** [comment]
Thought: leave this Python 3 only and merge to a new branch dev-py3 instead of master, where the rest of the development for a Python 3 release can go.

**Comment by madig** [comment]
Another thought: clean up test data? The various `*DesignspaceTest` folders could maybe be consolidated.

**Comment by madig** [comment]
Note: Use https://github.com/kvas-it/pytest-console-scripts.

**Comment by anthrotype** [comment]
> Note: Use https://github.com/kvas-it/pytest-console-scripts.

Actually about that, I ended up not using it anymore because I don’t like that it expects the scripts to be on $PATH. I don’t like that. I prefer that only the lib in on the PYTHONPATH for the tests to work. Also running subprocesses slows the tests too much.
If you are testing code within main(), keep calling that directly within the current process but monkeypatch  the logging configuration so it has no side effects on the other tests.
Otherwise make things modular and only unit tests those.

**Comment by madig** [comment]
Blargh... tox would probably come in handy...

**Comment by madig** [comment]
Rip out shiv making and the associated `after_success:` Travis step?

**Comment by anthrotype** [comment]
> Rip out shiv making and the associated after_success: Travis step?

i'd like the zipapps to stay. Not sure how many ppl use them though, but doesn't cost us much to make and publish them.

**Pull request merged**
