### PR TITLE
Use MathGlyph's "strict" flag

### LINKED ISSUE #961: fontmake -i destroys geometry when off curve points coincide with on curve points
The enclosed archive contains a .designspace file using two ufos. Running the "generate_instances.py" script writes a third master, based on the instance defined in the .designspace file.

The single glyph shape in those ufos have a cluster of points at each corner: an on-curve point, two off-curve point, another on-curve point, all at the same (x, y) position. (These could then be used to interpolate to a sharp corner with rounded-corner sources.)

The output of the script has all off-curve point stripped, so is no longer compatible with the sources. (The purpose here is to insert the generated ufo as a new source in the designspace.)

The fontmake instantiator uses `fontMath.MathGlyph` to do the interpolation, which messes with the topology of the shapes. In this case it filters out off-curve points that coincide with neighboring on-curve points.

`MathGlyph` recently got a "strict" flag to disable this behavior, and I think fontmake should use it.

That said, fontMath has a bug of its own here: https://github.com/robotools/fontMath/pull/305

[fontmake_test.zip](https://github.com/googlefonts/fontmake/files/10186163/fontmake_test.zip)

### PR DESCRIPTION
**Pull request by justvanrossum**
This fixes #961, and makes instantiator.py as strict as varLib when interpolating.

Depends on https://github.com/robotools/fontMath/pull/305, though, as fontMath doesn't properly propagate its "strict" flag down to copies.

So this PR should probably also update its fontMath version dependency, once a new fontMath is out.

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
LGTM, pending the other upstream change

**Comment by anthrotype** [comment]
ideally we also add a test perhaps based on the one from #961

**Comment by justvanrossum** [comment]
That failing lint check seems to demand passing the `strict` kw arg to builtin `zip`. This was introduced in 3.10, so as long as we need to support Python < 3.10, this lint check seems overly aggressive.

Not sure what to do about that in the context of this PR.

**Comment by anthrotype** [comment]
for now, we need to mute that overly zealous flake8 warning with https://github.com/googlefonts/ufo2ft/pull/684

**Comment by anthrotype** [comment]
i'm fine if you do that within this same PR, thanks!

**Comment by anthrotype** [comment]
oh jeez, codecov is hunting us again here.. ignore it for now, I can fix it on main

**Comment by justvanrossum** [comment]
Oh I just added a test! Sure, I'm fine with merging if you consider it fine.

**Comment by anthrotype** [comment]
can you please rebase on main? I think I fixed both flake8 and codecov issues

**Review by anthrotype — APPROVED** [review]
test also LGTM

**Comment by anthrotype** [comment]
just pushed v3.5.1 tag 👍

**Pull request merged**
